# Diálogos {.unnumbered}



**Conversa entre Salma (Egipto) e John (EUA)**

**John**: Ahlan, ezayek? - أهلا، إزيك؟  
**Salma**: Hi, ana kwayesa el7amdulelah, wenta? - هاي، أنا كويسة الحمد لله، و إنت؟  
**John**: Tamam el7amdulelah. - تمام الحمد لله  
**Salma**: Enta esmak eh? - إنت اسمك إيه؟  
**John**: Ana esmy John. Wenty? Enty esmek Sara? - أنا اسمي جون. و إنتي؟ إنتي اسمك سارة؟  
**Salma**: La2a, ana esmy Salma. Ana men Masr. Wenta meneen? - لأ، أنا اسمي سلمى. أنا من مصر. و إنت منين؟  
**John**: Ana men Amrika. Enty 3aysha feen ya Salma? - أنا من أمريكا. إنتي عايشة فين يا سلمى؟  
**Salma**: Ana 3aysha fi el kahera. Enta 3ayish fi New York? - أنا عايشة في القاهرة. إنت عايش في نيويورك؟  
**John**: La2a ana 3ayish fi Florida. 3andek kam sana? - لأ أنا عايش في فلوريدا. عندك كام سنة؟  
**Salma**: Ana 3andy 22 sana. Wenta 3andak kam sana? - أنا عندي ٢٢ سنة. و إنت عندك كام سنة؟  
**John**: Wana 3andy 30. Beteshta3'aly ya Salma? - و أنا عندي ٣٠. بتشتغلي يا سلمى؟  
**Salma**: La2a, ana msh bashta3'al ana badres. Wenta? - لأ، أنا مش بشتغل أنا بدرس. و إنت؟  
**John**: Ana bashta3'al mohandes. - أنا بشتغل مهندس  
**Salma**: Tamam. Ashofak bokra! - تمام. أشوفك بكرة!  
**John**: Ma3asallama! - مع السلامة!

---